name: githubpages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks-docusaurus:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Test Docusaurus Build
        run: |
          cd docusaurus-site
          if [ -e yarn.lock ]; then
          # yarn install --frozen-lockfile
          yarn install
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build

  deploy-to-github:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          cd docusaurus-site
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run deploy
